stages:
  - build
  - push

variables:
  DOCKER_HOST: "primeswu.azurecr.io"
  DOCKER_REPO_USER: "PrimeSWU"
  DOCKER_REPO_PASS: "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ"
  IMAGE_TAG: "optimize-prime"

before_script:
  - apt-get update -qq
  - apt-get install -yqq docker.io docker-compose
  - docker --version
  - docker-compose --version
  - echo "Container Registry/Image Tag = $CONTAINER_REGISTRY/$IMAGE_TAG"

build:
  stage: build
  script:
    - echo "Running docker-compose build -t $IMAGE_TAG"
    - docker-compose build -t $IMAGE_TAG"

push:
  stage: push
  script:
    - echo "Running docker push $CONTAINER_REGISTRY/$IMAGE_TAG"
    - docker push $CONTAINER_REGISTRY/$IMAGE_TAG 