stages:
  - build
  - push

variables:
  DOCKER_HOST: "primeswu.azurecr.io"
  DOCKER_REPO_USER: "PrimeSWU"
  DOCKER_REPO_PASS: "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ"
  IMAGE_TAG: optimize-prime

before_script:
  - apt-get update -qq
  - apt-get install -yqq docker.io

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG 

push:
  stage: push
  script:
    - docker push $CONTAINER_REGISTRY/$IMAGE_TAG 