stages:
  - build
  - push

variables:
  DOCKER_HOST: "primeswu.azurecr.io"
  DOCKER_REPO_USER: "PrimeSWU"
  DOCKER_REPO_PASS: "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ"
  IMAGE_TAG: "optimize-prime"

before_script:
  - cat /etc/*elease
  - apt-get update -qq
  - apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - apt update
  - apt install -y docker docker-compose git
  - echo "Container Registry/Image Tag = primeswu.azurecr.io/optimize-prime"

build:
  stage: build
  script:
    - docker-compose build 

push:
  stage: push
  script:
    - docker login -u PrimeSWU -p POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ primeswu.azurecr.io:80
    #    - cat dockerPassword.txt | docker login --username="PrimeSWU" --password-stdin
#    - docker login --usecho 'POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ' | docker login --username="PrimeSWU" --password-stdinername="PrimeSWU" -p "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ" https://primeswu.azurecr.io
    - docker tag optimizeprime_dotnet-webapi primeswu.azurecr.io/optimizeprime_dotnet-webapi:latest
    - docker push primeswu.azurecr.io/optimize-prime:latest
    - docker tag optimizeprime_nginx-angular primeswu.azurecr.io/optimizeprime_nginx-angular:latest
    - docker push primeswu.azurecr.io/optimizeprime_nginx-angular:latest
    - docker tag optimizeprime_postgres primeswu.azurecr.io/optimizeprime_postgres:latest
    - docker push primeswu.azurecr.io/optimizeprime_postgres:latest