# Validate with https://gitlab.com/sierrasystems/optimize-prime/-/ci/lint
image: docker:latest

services:
  - docker:dind

before_script:
  - apk add py-pip
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - docker info
  - docker-compose --version

build image:
  stage: build
  script:
    - docker-compose build
    - docker images
    - docker login https://primeswu.azurecr.io:443 --username PrimeSWU --password POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ
    - docker tag optimize-prime_dotnet-webapi primeswu.azurecr.io:443/optimize-prime_dotnet-webapi:latest
    #- docker push primeswu.azurecr.io:443/optimize-prime_dotnet-webapi:latest
    - docker tag optimize-prime_nginx-angular primeswu.azurecr.io:443/optimize-prime_nginx-angular:latest
    #- docker push primeswu.azurecr.io:443/optimize-prime_nginx-angular:latest
    - docker pull postgres:11.4
    - docker tag postgres:11.4 primeswu.azurecr.io:443/optimize-prime_postgres:latest
    #- docker push primeswu.azurecr.io:443/optimize-prime_postgres:latest