stages:
  - build
  - push

variables:
  DOCKER_HOST: "primeswu.azurecr.io"
  DOCKER_REPO_USER: "PrimeSWU"
  DOCKER_REPO_PASS: "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ"
  IMAGE_TAG: "optimize-prime"

before_script:
  - cat /etc/*elease
  - apt-get update -qq
  - apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - apt update
  - apt install -y docker docker-compose git
  - systemctl enable --now docker
  - usermod -aG docker $USER
  - docker version
  - docker-compose version
  - echo "Container Registry/Image Tag = $CONTAINER_REGISTRY/$IMAGE_TAG"

build:
  stage: build
  script:
    - echo "Running docker-compose build -t $IMAGE_TAG"
    - docker-compose build -t $IMAGE_TAG

push:
  stage: push
  script:
    - echo "Running docker push $DOCKER_HOST/$IMAGE_TAG"
    - docker push $DOCKER_HOST/$IMAGE_TAG 