stages:
  - build
  - push

variables:
  DOCKER_HOST: "primeswu.azurecr.io"
  DOCKER_REPO_USER: "PrimeSWU"
  DOCKER_REPO_PASS: "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ"
  IMAGE_TAG: "optimize-prime"

before_script:
  - cat /etc/*elease
  - apt-get update -qq
  - apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - apt update
  - apt install -y docker docker-compose git
  - echo "Container Registry/Image Tag = primeswu.azurecr.io/optimize-prime"

build:
  stage: build
  script:
    - echo "Running docker-compose build -t optimize-prime"
    - docker-compose build -t optimize-prime

push:
  stage: push
  script:
    - echo "Running docker push primeswu.azurecr.io/optimize-prime"
    - docker push primeswu.azurecr.io/optimize-prime