
image: docker

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_HOST: "primeswu.azurecr.io:80"
  DOCKER_REPO_USER: "PrimeSWU"
  DOCKER_REPO_PASS: "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ"
  IMAGE_TAG: "optimize-prime"

before_script:
  - apt-get update -qq
  - apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
  - chmod +x /tmp/docker-compose
#  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - /tmp/docker-compose --version
#  - cat /etc/*elease
#  - apt-get update -qq
#  - apt install -y apt-transport-https ca-certificates curl software-properties-common
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
#  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
#  - apt update
#  - apt install -y docker docker-compose git

build:
  stage: build
  script:
    - /tmp/docker-compose build 

push:
  stage: push
  script:
    - docker login https://primeswu.azurecr.io:443
    #    - cat dockerPassword.txt | docker login --username="PrimeSWU" --password-stdin
#    - docker login --usecho 'POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ' | docker login --username="PrimeSWU" --password-stdinername="PrimeSWU" -p "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ" http://primeswu.azurecr.io:80
    - docker tag optimizeprime_dotnet-webapi primeswu.azurecr.io:443/optimizeprime_dotnet-webapi:latest
    - docker push primeswu.azurecr.io:443/optimize-prime:latest
    - docker tag optimizeprime_nginx-angular primeswu.azurecr.io:443/optimizeprime_nginx-angular:latest
    - docker push primeswu.azurecr.io:443/optimizeprime_nginx-angular:latest
    - docker tag postgres:11.4 primeswu.azurecr.io:443/optimizeprime_postgres:latest
    - docker push primeswu.azurecr.io:443/optimizeprime_postgres:latest