# Validate with https://gitlab.com/sierrasystems/optimize-prime/-/ci/lint
image: docker:latest

services:
  - docker:dind

before_script:
  - apk add py-pip
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - docker info
  - docker-compose --version

build image:
  stage: build
  script:
    - docker-compose build
#    - docker login https://primeswu.azurecr.io:443
#    - cat dockerPassword.txt | docker login https://primeswu.azurecr.io:443 --username PrimeSWU --password-stdin
    - docker login https://primeswu.azurecr.io:443 --username PrimeSWU --password POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ
    - docker tag optimizeprime_dotnet-webapi primeswu.azurecr.io:443/optimizeprime_dotnet-webapi:latest
    - docker push primeswu.azurecr.io:443/optimize-prime:latest
    - docker tag optimizeprime_nginx-angular primeswu.azurecr.io:443/optimizeprime_nginx-angular:latest
    - docker push primeswu.azurecr.io:443/optimizeprime_nginx-angular:latest
    - docker tag postgres:11.4 primeswu.azurecr.io:443/optimizeprime_postgres:latest
    - docker push primeswu.azurecr.io:443/optimizeprime_postgres:latest
    - export DOCKER_HOST=40.122.108.127:2375
    - docker-compose up

# Credentials are in .docker/config.json