# Validate with https://gitlab.com/sierrasystems/optimize-prime/-/ci/lint
image: docker/compose:1.17.1

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

variables:
  DOCKER_HOST: "primeswu.azurecr.io:80"
  DOCKER_REPO_USER: "PrimeSWU"
  DOCKER_REPO_PASS: "POKaaZfvf8AhsgQNmUvjJLj+XbZQoIQJ"
  IMAGE_TAG: "optimize-prime"

build image:
  stage: build
  script:
    - docker-compose build
    - docker login https://primeswu.azurecr.io:443
    - docker tag optimizeprime_dotnet-webapi primeswu.azurecr.io:443/optimizeprime_dotnet-webapi:latest
    - docker push primeswu.azurecr.io:443/optimize-prime:latest
    - docker tag optimizeprime_nginx-angular primeswu.azurecr.io:443/optimizeprime_nginx-angular:latest
    - docker push primeswu.azurecr.io:443/optimizeprime_nginx-angular:latest
    - docker tag postgres:11.4 primeswu.azurecr.io:443/optimizeprime_postgres:latest
    - docker push primeswu.azurecr.io:443/optimizeprime_postgres:latest

# Credentials are in .docker/config.json